### ISSUE TITLE
Create a github action!

### ISSUE THREAD

**Issue by anirul** [anirul/Darwin#27]
We need to have a github action for the deployment on the server `darwin.onemoregame.ch:80` and we are pretty close to have this working see https://github.com/mlaager/Darwin. There is still some trouble at the end with the build. For a reason we don't get this refuse to build with the compiler it was using until then. You can inspire yourself from the github action for frame https://github.com/anirul/frame.

**Comment by RolfJordi** [comment]
this is done for me and working

the compile issue is fixed with a dockerbuild.

see [here](https://github.com/mlaager/Darwin/actions/runs/8436877313)

what ever is merged on mlaager/Darwin main branch on should be deployed on the azure webapp. but i have no way to verify it.

the build is using github cache for first build takes 40 minutes next 6 minutes (as long as vcpkg.conf is not changed)
